"""first revions

Revision ID: 810601fe4866
Revises: 
Create Date: 2022-03-02 15:57:51.492962

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '810601fe4866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark', sa.Column('mark', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('mark'),
                    sa.UniqueConstraint('mark'))
    op.create_table('role', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('name'))
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table(
        'schedule', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('term', sa.String(length=20), nullable=False),
        sa.Column('academic_year', sa.String(length=10), nullable=False),
        sa.Column('approval_date', sa.Date(), nullable=True),
        sa.Column('term_start', sa.Date(), nullable=False),
        sa.Column('term_end', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_table(
        'protocol', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('mark', sa.String(), nullable=True),
        sa.Column('justification', sa.String(), nullable=True),
        sa.Column('conclusions_and_recommendations',
                  sa.String(),
                  nullable=True),
        sa.Column('read_date', sa.Date(), nullable=True),
        sa.Column('is_approved', sa.Boolean(), nullable=False),
        sa.Column('is_sent', sa.Boolean(), nullable=False),
        sa.Column('presentation_mark_fk', sa.Float(), nullable=True),
        sa.Column('explanation_mark_fk', sa.Float(), nullable=True),
        sa.Column('realization_mark_fk', sa.Float(), nullable=True),
        sa.Column('inspiration_mark_fk', sa.Float(), nullable=True),
        sa.Column('participation_mark_fk', sa.Float(), nullable=True),
        sa.Column('use_of_learning_methods_mark_fk', sa.Float(),
                  nullable=True),
        sa.Column('use_of_tools_mark_fk', sa.Float(), nullable=True),
        sa.Column('control_mark_fk', sa.Float(), nullable=True),
        sa.Column('creation_mark_fk', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['control_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['creation_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['explanation_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['inspiration_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['participation_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['presentation_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['realization_mark_fk'],
            ['mark.mark'],
        ),
        sa.ForeignKeyConstraint(
            ['use_of_learning_methods_mark_fk'],
            ['mark.mark'],
        ), sa.ForeignKeyConstraint(
            ['use_of_tools_mark_fk'],
            ['mark.mark'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_protocol_id'), 'protocol', ['id'], unique=False)
    op.create_table('user', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('role_fk', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['role_fk'],
                        ['role.id'],
                    ), sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login'))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_fk'), 'user', ['role_fk'], unique=False)
    op.create_table(
        'appeal', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_fk', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('protocol_fk', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['protocol_fk'],
            ['protocol.id'],
        ), sa.ForeignKeyConstraint(
            ['user_fk'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_appeal_id'), 'appeal', ['id'], unique=False)
    op.create_index(op.f('ix_appeal_protocol_fk'),
                    'appeal', ['protocol_fk'],
                    unique=False)
    op.create_index(op.f('ix_appeal_user_fk'),
                    'appeal', ['user_fk'],
                    unique=False)
    op.create_table('audit_commission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_fk', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_fk'],
                        ['user.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_audit_commission_id'),
                    'audit_commission', ['id'],
                    unique=False)
    op.create_index(op.f('ix_audit_commission_user_fk'),
                    'audit_commission', ['user_fk'],
                    unique=False)
    op.create_table(
        'course', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_fk', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('level_and_form_of_study', sa.String(), nullable=False),
        sa.Column('didactic_form', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('participants_number', sa.Integer(), nullable=False),
        sa.Column('place', sa.String(), nullable=False),
        sa.Column('organizational_entity', sa.String(), nullable=False),
        sa.Column('term', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_fk'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('code'),
        sa.UniqueConstraint('name'))
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_user_fk'),
                    'course', ['user_fk'],
                    unique=False)
    op.create_table(
        'audit', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('audit_commission_fk', sa.Integer(), nullable=False),
        sa.Column('schedule_fk', sa.Integer(), nullable=False),
        sa.Column('user_fk', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('course_fk', sa.Integer(), nullable=False),
        sa.Column('protocol_fk', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['audit_commission_fk'],
            ['audit_commission.id'],
        ), sa.ForeignKeyConstraint(
            ['course_fk'],
            ['course.id'],
        ), sa.ForeignKeyConstraint(
            ['protocol_fk'],
            ['protocol.id'],
        ), sa.ForeignKeyConstraint(
            ['schedule_fk'],
            ['schedule.id'],
        ), sa.ForeignKeyConstraint(
            ['user_fk'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_audit_audit_commission_fk'),
                    'audit', ['audit_commission_fk'],
                    unique=False)
    op.create_index(op.f('ix_audit_course_fk'),
                    'audit', ['course_fk'],
                    unique=False)
    op.create_index(op.f('ix_audit_id'), 'audit', ['id'], unique=False)
    op.create_index(op.f('ix_audit_protocol_fk'),
                    'audit', ['protocol_fk'],
                    unique=False)
    op.create_index(op.f('ix_audit_schedule_fk'),
                    'audit', ['schedule_fk'],
                    unique=False)
    op.create_index(op.f('ix_audit_user_fk'),
                    'audit', ['user_fk'],
                    unique=False)
    op.create_table(
        'audit_commission_user',
        sa.Column('audit_commission_fk', sa.Integer(), nullable=False),
        sa.Column('user_fk', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['audit_commission_fk'],
            ['audit_commission.id'],
        ), sa.ForeignKeyConstraint(
            ['user_fk'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('audit_commission_fk', 'user_fk'))
    op.create_index(op.f('ix_audit_commission_user_audit_commission_fk'),
                    'audit_commission_user', ['audit_commission_fk'],
                    unique=False)
    op.create_index(op.f('ix_audit_commission_user_user_fk'),
                    'audit_commission_user', ['user_fk'],
                    unique=False)
    op.create_table('user_course',
                    sa.Column('course_fk', sa.Integer(), nullable=False),
                    sa.Column('user_fk', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['course_fk'],
                        ['course.id'],
                    ), sa.ForeignKeyConstraint(
                        ['user_fk'],
                        ['user.id'],
                    ), sa.PrimaryKeyConstraint('course_fk', 'user_fk'))
    op.create_index(op.f('ix_user_course_course_fk'),
                    'user_course', ['course_fk'],
                    unique=False)
    op.create_index(op.f('ix_user_course_user_fk'),
                    'user_course', ['user_fk'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course_user_fk'), table_name='user_course')
    op.drop_index(op.f('ix_user_course_course_fk'), table_name='user_course')
    op.drop_table('user_course')
    op.drop_index(op.f('ix_audit_commission_user_user_fk'),
                  table_name='audit_commission_user')
    op.drop_index(op.f('ix_audit_commission_user_audit_commission_fk'),
                  table_name='audit_commission_user')
    op.drop_table('audit_commission_user')
    op.drop_index(op.f('ix_audit_user_fk'), table_name='audit')
    op.drop_index(op.f('ix_audit_schedule_fk'), table_name='audit')
    op.drop_index(op.f('ix_audit_protocol_fk'), table_name='audit')
    op.drop_index(op.f('ix_audit_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_course_fk'), table_name='audit')
    op.drop_index(op.f('ix_audit_audit_commission_fk'), table_name='audit')
    op.drop_table('audit')
    op.drop_index(op.f('ix_course_user_fk'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_audit_commission_user_fk'),
                  table_name='audit_commission')
    op.drop_index(op.f('ix_audit_commission_id'),
                  table_name='audit_commission')
    op.drop_table('audit_commission')
    op.drop_index(op.f('ix_appeal_user_fk'), table_name='appeal')
    op.drop_index(op.f('ix_appeal_protocol_fk'), table_name='appeal')
    op.drop_index(op.f('ix_appeal_id'), table_name='appeal')
    op.drop_table('appeal')
    op.drop_index(op.f('ix_user_role_fk'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_protocol_id'), table_name='protocol')
    op.drop_table('protocol')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_table('mark')
    # ### end Alembic commands ###
